name: Deploy to Droplet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync
        
    - name: Deploy to Droplet
      run: |
        # Ensure the remote directory exists
        ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} "mkdir -p /opt/mb-final"
        
        # Copy files to the Droplet
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
          --exclude='.git' \
          --exclude='node_modules' \
          --exclude='.nuxt' \
          --exclude='.output' \
          --exclude='.github' \
          ./ root@${{ secrets.DROPLET_IP }}:/opt/mb-final/
          
        # Make deploy script executable and run it
        ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} "cd /opt/mb-final && \
          chmod +x deploy.sh && \
          ./deploy.sh"
      
    - name: Verify deployment
      run: |
        echo "Deployment complete! Verifying..."
        curl -s http://${{ secrets.DROPLET_IP }}/api/health || echo "Deployment verification failed"
