name: Deploy to Droplet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync
        
    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        # Write the key with proper newlines
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        # Test key format
        ssh-keygen -l -f ~/.ssh/deploy_key || echo "Key format check failed"
        # Configure SSH
        echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config
        
    - name: Deploy to Droplet
      run: |
        # Ensure the remote directory exists
        ssh -i ~/.ssh/deploy_key root@${{ secrets.DROPLET_IP }} "mkdir -p /opt/mb-final"
        
        # Copy files to the Droplet
        rsync -avz -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
          --exclude='.git' \
          --exclude='node_modules' \
          --exclude='.nuxt' \
          --exclude='.output' \
          --exclude='.github' \
          ./ root@${{ secrets.DROPLET_IP }}:/opt/mb-final/
          
        # Make deploy script executable and run it
        ssh -i ~/.ssh/deploy_key root@${{ secrets.DROPLET_IP}} "
          cd /opt/mb-final && \
          chmod +x deploy.sh && \
          ./deploy.sh
        "
      
    - name: Verify deployment
      run: |
        echo "Deployment complete! Verifying..."
        curl -s http://${{ secrets.DROPLET_IP }}/api/health || echo "Deployment verification failed"
